// 163 bairros oficiais do Rio de Janeiro organizados por zona
export interface Neighborhood {
  name: string;
  zone: string;
}

export const RIO_NEIGHBORHOODS: Neighborhood[] = [
  // Centro
  { name: 'Centro', zone: 'Centro' },
  { name: 'Castelo', zone: 'Centro' },
  { name: 'Cinelândia', zone: 'Centro' },
  { name: 'Glória', zone: 'Centro' },
  { name: 'Lapa', zone: 'Centro' },
  { name: 'Saúde', zone: 'Centro' },
  { name: 'Santa Teresa', zone: 'Centro' },
  { name: 'Catumbi', zone: 'Centro' },
  { name: 'Rio Comprido', zone: 'Centro' },
  { name: 'Estácio', zone: 'Centro' },
  { name: 'São Cristóvão', zone: 'Centro' },
  { name: 'Benfica', zone: 'Centro' },
  { name: 'Gamboa', zone: 'Centro' },
  { name: 'Santo Cristo', zone: 'Centro' },
  { name: 'Cidade Nova', zone: 'Centro' },
  { name: 'Caju', zone: 'Centro' },
  { name: 'Mangueira', zone: 'Centro' },

  // Zona Sul
  { name: 'Flamengo', zone: 'Zona Sul' },
  { name: 'Botafogo', zone: 'Zona Sul' },
  { name: 'Laranjeiras', zone: 'Zona Sul' },
  { name: 'Catete', zone: 'Zona Sul' },
  { name: 'Cosme Velho', zone: 'Zona Sul' },
  { name: 'Urca', zone: 'Zona Sul' },
  { name: 'Copacabana', zone: 'Zona Sul' },
  { name: 'Ipanema', zone: 'Zona Sul' },
  { name: 'Leblon', zone: 'Zona Sul' },
  { name: 'Lagoa', zone: 'Zona Sul' },
  { name: 'Jardim Botânico', zone: 'Zona Sul' },
  { name: 'Gávea', zone: 'Zona Sul' },
  { name: 'Vidigal', zone: 'Zona Sul' },
  { name: 'São Conrado', zone: 'Zona Sul' },
  { name: 'Humaitá', zone: 'Zona Sul' },
  { name: 'Rocinha', zone: 'Zona Sul' },

  // Grande Tijuca
  { name: 'Tijuca', zone: 'Grande Tijuca' },
  { name: 'Alto da Boa Vista', zone: 'Grande Tijuca' },
  { name: 'Andaraí', zone: 'Grande Tijuca' },
  { name: 'Grajaú', zone: 'Grande Tijuca' },
  { name: 'Maracanã', zone: 'Grande Tijuca' },
  { name: 'Praça da Bandeira', zone: 'Grande Tijuca' },
  { name: 'Vila Isabel', zone: 'Grande Tijuca' },
  { name: 'Saens Peña', zone: 'Grande Tijuca' },

  // Zona Norte
  { name: 'Méier', zone: 'Zona Norte' },
  { name: 'Engenho de Dentro', zone: 'Zona Norte' },
  { name: 'Engenho Novo', zone: 'Zona Norte' },
  { name: 'Rocha', zone: 'Zona Norte' },
  { name: 'Sampaio', zone: 'Zona Norte' },
  { name: 'Cachambi', zone: 'Zona Norte' },
  { name: 'Todos os Santos', zone: 'Zona Norte' },
  { name: 'Piedade', zone: 'Zona Norte' },
  { name: 'Pilares', zone: 'Zona Norte' },
  { name: 'São Francisco Xavier', zone: 'Zona Norte' },
  { name: 'Abolição', zone: 'Zona Norte' },
  { name: 'Água Santa', zone: 'Zona Norte' },
  { name: 'Encantado', zone: 'Zona Norte' },
  { name: 'Lins de Vasconcelos', zone: 'Zona Norte' },
  { name: 'Riachuelo', zone: 'Zona Norte' },
  { name: 'Del Castilho', zone: 'Zona Norte' },
  { name: 'Inhaúma', zone: 'Zona Norte' },
  { name: 'Engenho da Rainha', zone: 'Zona Norte' },
  { name: 'Tomás Coelho', zone: 'Zona Norte' },
  { name: 'Vicente de Carvalho', zone: 'Zona Norte' },
  { name: 'Vaz Lobo', zone: 'Zona Norte' },
  { name: 'Colégio', zone: 'Zona Norte' },
  { name: 'Irajá', zone: 'Zona Norte' },
  { name: 'Turiaçu', zone: 'Zona Norte' },
  { name: 'Rocha Miranda', zone: 'Zona Norte' },
  { name: 'Honório Gurgel', zone: 'Zona Norte' },
  { name: 'Oswaldo Cruz', zone: 'Zona Norte' },
  { name: 'Cavalcanti', zone: 'Zona Norte' },
  { name: 'Madureira', zone: 'Zona Norte' },
  { name: 'Cascadura', zone: 'Zona Norte' },
  { name: 'Campinho', zone: 'Zona Norte' },
  { name: 'Marechal Hermes', zone: 'Zona Norte' },
  { name: 'Bento Ribeiro', zone: 'Zona Norte' },
  { name: 'Cosmos', zone: 'Zona Norte' },
  { name: 'Guadalupe', zone: 'Zona Norte' },
  { name: 'Anchieta', zone: 'Zona Norte' },
  { name: 'Pavuna', zone: 'Zona Norte' },
  { name: 'Vigário Geral', zone: 'Zona Norte' },
  { name: 'Parada de Lucas', zone: 'Zona Norte' },
  { name: 'Penha', zone: 'Zona Norte' },
  { name: 'Penha Circular', zone: 'Zona Norte' },
  { name: 'Brás de Pina', zone: 'Zona Norte' },
  { name: 'Cordovil', zone: 'Zona Norte' },
  { name: 'Jardim América', zone: 'Zona Norte' },
  { name: 'Olaria', zone: 'Zona Norte' },
  { name: 'Ramos', zone: 'Zona Norte' },
  { name: 'Bonsucesso', zone: 'Zona Norte' },
  { name: 'Manguinhos', zone: 'Zona Norte' },
  { name: 'Maré', zone: 'Zona Norte' },

  // Barra da Tijuca e Jacarepaguá
  { name: 'Barra da Tijuca', zone: 'Barra/Jacarepaguá' },
  { name: 'Recreio dos Bandeirantes', zone: 'Barra/Jacarepaguá' },
  { name: 'Joá', zone: 'Barra/Jacarepaguá' },
  { name: 'Barra Olímpica', zone: 'Barra/Jacarepaguá' },
  { name: 'Jacarepaguá', zone: 'Barra/Jacarepaguá' },
  { name: 'Freguesia (Jacarepaguá)', zone: 'Barra/Jacarepaguá' },
  { name: 'Pechincha', zone: 'Barra/Jacarepaguá' },
  { name: 'Taquara', zone: 'Barra/Jacarepaguá' },
  { name: 'Tanque', zone: 'Barra/Jacarepaguá' },
  { name: 'Curicica', zone: 'Barra/Jacarepaguá' },
  { name: 'Praça Seca', zone: 'Barra/Jacarepaguá' },
  { name: 'Vila Valqueire', zone: 'Barra/Jacarepaguá' },
  { name: 'Gardênia Azul', zone: 'Barra/Jacarepaguá' },
  { name: 'Camorim', zone: 'Barra/Jacarepaguá' },
  { name: 'Vargem Grande', zone: 'Barra/Jacarepaguá' },
  { name: 'Vargem Pequena', zone: 'Barra/Jacarepaguá' },
  { name: 'Grumari', zone: 'Barra/Jacarepaguá' },
  { name: 'Itanhangá', zone: 'Barra/Jacarepaguá' },
  { name: 'Anil', zone: 'Barra/Jacarepaguá' },
  { name: 'Rio das Pedras', zone: 'Barra/Jacarepaguá' },
  { name: 'Cidade de Deus', zone: 'Barra/Jacarepaguá' },
  { name: 'Muzema', zone: 'Barra/Jacarepaguá' },

  // Zona Oeste
  { name: 'Bangu', zone: 'Zona Oeste' },
  { name: 'Campo Grande', zone: 'Zona Oeste' },
  { name: 'Realengo', zone: 'Zona Oeste' },
  { name: 'Santa Cruz', zone: 'Zona Oeste' },
  { name: 'Sepetiba', zone: 'Zona Oeste' },
  { name: 'Guaratiba', zone: 'Zona Oeste' },
  { name: 'Pedra de Guaratiba', zone: 'Zona Oeste' },
  { name: 'Barra de Guaratiba', zone: 'Zona Oeste' },
  { name: 'Senador Vasconcelos', zone: 'Zona Oeste' },
  { name: 'Inhoaíba', zone: 'Zona Oeste' },
  { name: 'Santíssimo', zone: 'Zona Oeste' },
  { name: 'Senador Camará', zone: 'Zona Oeste' },
  { name: 'Padre Miguel', zone: 'Zona Oeste' },
  { name: 'Deodoro', zone: 'Zona Oeste' },
  { name: 'Vila Militar', zone: 'Zona Oeste' },
  { name: 'Magalhães Bastos', zone: 'Zona Oeste' },
  { name: 'Sulacap', zone: 'Zona Oeste' },
  { name: 'Campo dos Afonsos', zone: 'Zona Oeste' },

  // Ilha do Governador
  { name: 'Ilha do Governador', zone: 'Ilha do Governador' },
  { name: 'Bancários', zone: 'Ilha do Governador' },
  { name: 'Cacuia', zone: 'Ilha do Governador' },
  { name: 'Freguesia (Ilha)', zone: 'Ilha do Governador' },
  { name: 'Galeão', zone: 'Ilha do Governador' },
  { name: 'Jardim Carioca', zone: 'Ilha do Governador' },
  { name: 'Jardim Guanabara', zone: 'Ilha do Governador' },
  { name: 'Moneró', zone: 'Ilha do Governador' },
  { name: 'Pitangueiras', zone: 'Ilha do Governador' },
  { name: 'Portuguesa', zone: 'Ilha do Governador' },
  { name: 'Praia da Bandeira', zone: 'Ilha do Governador' },
  { name: 'Ribeira', zone: 'Ilha do Governador' },
  { name: 'Tauá', zone: 'Ilha do Governador' },
  { name: 'Zumbi', zone: 'Ilha do Governador' },
];

export const ZONES = [...new Set(RIO_NEIGHBORHOODS.map((n) => n.zone))];

export const NEIGHBORHOOD_NAMES = RIO_NEIGHBORHOODS.map((n) => n.name).sort((a, b) =>
  a.localeCompare(b, 'pt-BR'),
);
